name: Prevent scheduled workflow from being automatically disabled

on:
  schedule:
    - cron: "40 5 4,29 * *"
  workflow_dispatch:

concurrency:
  group: keepalive
  cancel-in-progress: false

jobs:
  keepalive:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trigger nextjs workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run nextjs.yml
