name: Prevent scheduled workflow from being automatically disabled

on:
  # 定期実行
  schedule:
    # UTCで実行されているのでJST AM0時過ぎに実行される
    # - cron: "10 15 1 * *"
    # - cron: "10 15 30 * *"
    - cron: "05 8 29 * *"

  # 手動実行
  workflow_dispatch:

concurrency:
  group: keepalive
  cancel-in-progress: false

jobs:
  # nextjs workflowを実行する
  keepalive:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trigger nextjs workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run nextjs.yml
